spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/acore_auth
    username: root
    password: Loquendo96@
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8080
application:
  account:
    api-key: tt8wt17cx6nb0lb
    username: mschitiva68@gmail.com
    password: sebas
  urls:
    wow-libre-login: http://localhost:8090/api/auth/login
    wow-libre-server: http://localhost:8090/api/server/key
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days