spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/acore_auth
      username: root
      password: Loquendo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/acore_characters
      username: root
      password: Loquendo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8090
application:
  credentials:
    command:
      username: 'admin'
      password: 'admin'
  account:
    api-key: 91z76oy42i159uc
    username: mschitiva68@gmail.com
    password: 'sebas'
  urls:
    wow-libre-login: http://localhost:8091/core/api/auth/login
    wow-libre-server: http://localhost:8091/core/api/server/key
  security:
    jwt:
      secret-key: A3F1E4B2D0A728C9F54D8B32C7A59A7D0B9A8F94D1F6C762E7DA56231988C158
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/acore_auth
      username: root
      password: Jeronimo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/acore_characters
      username: root
      password: Jeronimo96@
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  address: 0.0.0.0
  port: 8090
application:
  credentials:
    command:
      username: "machitiva"
      password: "wowlibre"
  account:
    api-key: "okdasodiasjdi"
    username: "mschitiva68@gmail.com"
    password: "sebas"
  urls:
    wow-libre-login: https://api.wowlibre.com/core/api/auth/login
    wow-libre-server: https://api.wowlibre.com/core/api/server/key
  security:
    jwt:
      secret-key: D7A4C3F9E5D2A688B9D1F7C2E9D7A9F3C0E0F6B6F2C8A7D1E9F6D5A8B1F5D6E
      expiration: 604800000  # 7 day
      refresh-token:
        expiration: 1209600000 # 14 días